version: "3.2"
services:
  notification-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpw
      MYSQL_DATABASE: PugChat_notification_ms_development
      MYSQL_USER: sa
      MYSQL_PASSWORD: 2019ii
    ports: 
      - "3308:3306"

  notification-ms:
    build: .
    command: rails s -b '0.0.0.0'
    ports:
      - "4001:3000"